repos:
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.5.3
    hooks:
      - id: prettier
        types_or:
          - toml
          - css
          - json
          - json5
          - markdown
          - yaml
        additional_dependencies:
          - prettier
          - prettier-plugin-toml
        minimum_pre_commit_version: 2.9.0
        args:
          - --cache
          - --cache-location=.prettier-cache
          - --ignore-path=.gitignore
        exclude: ^tests
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
      - id: cargo-check
      - id: clippy
        args: [--, -Dwarnings]
  - repo: https://github.com/mondeja/rust-pc-hooks
    rev: v1.3.0
    hooks:
      - id: cargo-readme
        alias: cargo-readme-workspace
        name: cargo-readme-workspace
        args:
          - --project-root=rust
          - --output=../README.md
          - --template=../README.tpl
      - id: cargo-readme
        alias: cargo-readme-rust
        name: cargo-readme-rust
        args:
          - --project-root=rust
          - --output=README.md
          - --template=README.tpl
      - id: cargo-readme
        alias: cargo-readme-python
        name: cargo-readme-python
        args:
          - --project-root=rust
          - --output=../python/README.md
          - --template=../python/README.tpl
