repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        args:
          - --cache
          - --cache-location=.prettier-cache
          - --ignore-path=.gitignore
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
      - id: cargo-check
      - id: clippy
        args: [--, -Dwarnings]
  - repo: https://github.com/mondeja/rust-pc-hooks
    rev: v1.3.0
    hooks:
      - id: cargo-readme
        alias: cargo-readme-workspace
        name: cargo-readme-workspace
        args:
          - --project-root=rust
          - --output=../README.md
          - --template=../README.tpl
      - id: cargo-readme
        alias: cargo-readme-rust
        name: cargo-readme-rust
        args:
          - --project-root=rust
          - --output=README.md
          - --template=README.tpl
      - id: cargo-readme
        alias: cargo-readme-python
        name: cargo-readme-python
        args:
          - --project-root=rust
          - --output=../python/README.md
          - --template=../python/README.tpl
      - id: cargo-machete
      - id: lychee
