# md-ulb-pwrap

<!-- This file has been autogenerated.
To update it, change the content of `rust/src/lib.rs`
and run `pre-commit run -a cargo-readme`
-->

{{readme}}

## Usage

```bash
cargo add md-ulb-pwrap
```

````rust
use md_ulb_pwrap::ulb_wrap_paragraph;

assert_eq!(
    ulb_wrap_paragraph(
        &"aaa ``` ``  ` a b c ``` ccc",
        3,
        3,
    ),
    "aaa\n``` ``  ` a b c ```\nccc",
);
````
